#!/usr/bin/perl

if($ARGV[0] eq "-l"){
	$l_switch_on = 1;
	shift @ARGV;
	$grep_expression = $ARGV[0];
	shift @ARGV;
}
else {
	$l_switch_on = 0;
	$grep_expression = $ARGV[0];
	shift @ARGV;
}

foreach $file_dir (@ARGV){
	@files_in_dir = `find $file_dir`; #finds all files in a directory, if the $arg is a file it returns the file
	chomp(@files_in_dir);
	@tfiles_in_dir = grep(-T, @files_in_dir);
	foreach $grep_file (@tfiles_in_dir){
		open($fh, "<", "$grep_file") or die "Can't open $grep_file";
		@contents = grep(/$grep_expression/, <$fh>);
		chomp(@contents);
		if($l_switch_on == 1 && $#contents > 0){
			print "$grep_file\n";
		}
		else{
			foreach $line_found(@contents){
				print "$grep_file:$line_found\n";
			}
		}
	
	}
}
